title: chraebsli Tutorials
description:
social:
  github:
    username: chraebsli
    repository: chraebsli/tutorials
  name: Nicholas Krebs
  email: nicholas.joel.krebs@gmail.com
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      author: Nicholas Krebs
plugins:
  - jekyll-sitemap
