# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Configuration options can be accessed in any template with {{ site.title }},
# {{ site.email }}, and so on

# Site settings
title: &title Coding Crab Blog
subtitle: &subtitle "Blogs about web development and other IT stuff"
description: &description "Blogs about web development and other IT stuff"
author_name: &author Nicholas Krebs
email: &email nicholas@nicholas-krebs.ch
github_username: &github chraebsli
repository: &repository chraebsli/coding-crab-blog
locale: "en-US"
url: https://blog.chraebsli.dev

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.23.0
minimal_mistakes_skin: dark # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title_separator: "-"
search: true
include:
  - _pages
paginate: 10 # amount of posts to show
timezone: Europe/Zurich # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%-d %b %Y %H:%M"

# Structures
paginate_path: /page:num/
permalink: /:categories/:title/
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# CSS / SASS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Compressing
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Kramdown
kramdown:
  toc_levels: 1..4
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "Table of Contents"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Comments
comments:
  provider: giscus
  giscus:
    repo: *repository
    repo_id: R_kgDOI9p5Ww
    category_name: Blog Comments
    category_id: DIC_kwDOI9p5W84CUcYE
    discussion_term: pathname # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: 1 # '1' for enabled (default), '0' for disabled
    theme: transparent_dark # "light" (default), "dark", "dark_dimmed", "transparent_dark", "c"
    emit_metadata: 1
    input_position: top
    lang: en
    loading: lazy

# Analytics
analytics:
  provider: custom
  digistats:
    tracking_id: ZwSg9rf6GA
  umami:
    tracking_id: 7cd890e5-6ee0-45f2-b0a4-0d503793498d

# Social Media Profiles
links:
  - website: &websiteURL "https://nicholas-krebs.ch"
  - github: &githubURL "https://github.com/chraebsli"
  - mastodon: &mastodonURL "https://techhub.social/@chraebsli"
  - email: &emailURL "mailto:nicholas@nicholas-krebs.ch"
author:
  name: *author
  avatar: "/assets/images/bio-photo.jpg"
  bio: "IT enthusiast & web developer from Switzerland"
  location: "Switzerland"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: *websiteURL
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: *githubURL
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: *mastodonURL
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: *emailURL
social:
  name: *author
  links:
    - *githubURL
    - *mastodonURL
    - *emailURL
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: *websiteURL
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: *emailURL
